editor:
  /Applications/Emacs.app/Contents/MacOS/Emacs-10.7 -nw

hadoop_repo_directory:
  <your directory of the hadoop repository>

jira_base_uri: https://issues.apache.org/jira

git_repo_name: origin
git_binary: /usr/bin/git

test_compile_command:
  /usr/local/bin/mvn clean install -q -DskipTests -Dmaven.javadoc.skip=true -Djava.awt.headless=true

jira_username: <your jira ID>
jira_password: <your jira password>
